kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kogito-serverless-operator-leases
  labels:
    app: "kogito-serverless-operator"
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch