apiVersion: sw.kogito.kie.org/v08
kind: KogitoServerlessBuild
metadata:
  name: kogitoserverlessbuild-sample
spec:
  cluster: Kubernetes
  platform:
    registry:
      address: quay.io/dsalerno
      secret: regcred
